<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="3dof_planar">
  <xacro:macro name="three_dof_planar_arm" params="arm_id:='three_dof_planar' connected_to:='' xyz:='0 0 0' rpy:='0 0 0'">
    <xacro:unless value="${not connected_to}">
      <joint name="${arm_id}_joint_${connected_to}" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_link0"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>

    <!-- for simulation -->
    <xacro:property name="joint_damping" value="0.0"/>
    <xacro:property name="link1_length" value="0.5"/>
    <xacro:property name="link2_length" value="0.3"/>
    <xacro:property name="link3_length" value="0.2"/>
    <!-- end for simulation -->

    <link name="${arm_id}_link0">
      <visual>
        <geometry>
	   <box size="0.1 0.1 0.1"/>
        </geometry>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.05"/>
      </visual>
      <collision>
        <geometry>
	   <box size="0.1 0.1 0.1"/>
        </geometry>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.05"/>
      </collision>

      <!-- for simulation -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="5.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <!-- end for simulation -->
    </link>
    
    <link name="${arm_id}_link1">
      <visual>
        <geometry>
		<cylinder length="${link1_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link1_length/2} 0.0 0.0"/>
      </visual>
      <collision>
        <geometry>
		<cylinder length="${link1_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link1_length/2} 0.0 0.0"/>
      </collision>

      <!-- for simulation -->
      <inertial>
        <origin xyz="${link1_length/2} 0.0 0.0" rpy="0 0 0" />
        <mass value="1.0" />
        <!--inertia izz="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" ixx="0.0002" /-->
        <inertia izz="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" ixx="0.0" />
      </inertial>
      <!-- end for simulation -->
    </link>

    <joint name="${arm_id}_joint1" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.9" soft_upper_limit="1.9"/>
      <origin rpy="0 0 ${pi/4}" xyz="0 0 0.05"/>
      <parent link="${arm_id}_link0"/>
      <child link="${arm_id}_link1"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" lower="-2" upper="2" velocity="2.1750"/>
      <!-- for simulation -->
      <dynamics damping="${joint_damping}" friction="0.546"/>
      <!-- end for simulation -->
    </joint>
    
    <link name="${arm_id}_link2">
      <visual>
        <geometry>
		<cylinder length="${link2_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link2_length/2} 0.0 0.0"/>
      </visual>
      <collision>
        <geometry>
		<cylinder length="${link2_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link2_length/2} 0.0 0.0"/>
      </collision>

      <!-- for simulation -->
      <inertial>
        <origin xyz="${link2_length/2} 0.0 0.0" rpy="0 0 0" />
        <mass value="0.6" />
        <!--inertia izz="0.00456" ixy="0.0" ixz="0.0" iyy="0.00456" iyz="0.0" ixx="0.0001" /-->
        <inertia izz="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" ixx="0.0" />
      </inertial>
      <!-- end for simulation -->
    </link>

    <joint name="${arm_id}_joint2" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.9" soft_upper_limit="1.9"/>
      <origin rpy="0 0 ${-pi/8}" xyz="${link1_length} 0 0"/>
      <parent link="${arm_id}_link1"/>
      <child link="${arm_id}_link2"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" lower="-2" upper="2" velocity="2.1750"/>
      <!-- for simulation -->
      <dynamics damping="${joint_damping}" friction="0.546"/>
      <!-- end for simulation -->
    </joint>
    
    <link name="${arm_id}_link3">
      <visual>
        <geometry>
		<cylinder length="${link3_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link3_length/2} 0.0 0.0"/>
      </visual>
      <collision>
        <geometry>
		<cylinder length="${link3_length}" radius="0.02"/>
        </geometry>
	<origin rpy="0.0 ${pi/2} 0.0" xyz="${link3_length/2} 0.0 0.0"/>
      </collision>

      <!-- for simulation -->
      <inertial>
        <origin xyz="${link3_length/2} 0.0 0.0" rpy="0 0 0" />
        <mass value="0.3" />
        <!--inertia izz="0.00103" ixy="0.0" ixz="0.0" iyy="0.00103" iyz="0.0" ixx="0.00006" /-->
        <inertia izz="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" ixx="0.0" />
      </inertial>
      <!-- end for simulation -->
    </link>

    <joint name="${arm_id}_joint3" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.9" soft_upper_limit="1.9"/>
      <origin rpy="0 0 ${-pi/8}" xyz="${link2_length} 0 0"/>
      <parent link="${arm_id}_link2"/>
      <child link="${arm_id}_link3"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" lower="-2" upper="2" velocity="2.1750"/>
      <!-- for simulation -->
      <dynamics damping="${joint_damping}" friction="0.546"/>
      <!-- end for simulation -->
    </joint>

    <link name="${arm_id}_eef"> 
      <!-- for simulation --> 
      <inertial> 
        <origin xyz="0 0 0" rpy="0 0 0" /> 
        <mass value="0.0" /> 
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" /> 
      </inertial> 
      <!-- end for simulation --> 
    </link> 
    <joint name="${arm_id}_eef_fixed" type="fixed"> 
	    <origin rpy="0 0 0" xyz="${link3_length} 0 0"/> 
      <parent link="${arm_id}_link3"/> 
      <child link="${arm_id}_eef"/> 
      <axis xyz="0 0 0"/> 
    </joint> 


  </xacro:macro>
</robot>
