# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

# HiQP Effort Controller ----------------------------------------
hiqp_joint_effort_controller:
  type: hiqp_ros/HiQPJointEffortController
  visualization_publish_rate: 25 #Hz
  load_primitives_from_tf: true
  marker_prefix: ""
  model_based: true
  chain_root: "three_dof_planar_link0"
  chain_tip: "three_dof_planar_eef"
  joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3
  task_monitoring:
    active: 1
    publish_rate: 150.0
  kv: 
    - 30.0
    - 30.0
    - 30.0
  kd: 
    - 11.0
    - 11.0
    - 11.0
