# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3

# HiQP Effort Controller ----------------------------------------
hiqp_joint_effort_controller:
  type: hiqp_ros/HiQPJointEffortController
  visualization_publish_rate: 25 #Hz
  load_primitives_from_tf: true
  marker_prefix: ""
  model_based: true
  chain_root: "three_dof_planar_link0"
  chain_tip: "three_dof_planar_eef"
  joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3
  task_monitoring:
    active: 1
    publish_rate: 150.0
  kv: 
    - 30.0
    - 30.0
    - 30.0
  kd: 
    - 11.0
    - 11.0
    - 11.0

# HiQP Velocity Controller ----------------------------------------
hiqp_joint_velocity_controller:
  type: hiqp_ros/HiQPJointVelocityController
  visualization_publish_rate: 25 #Hz
  load_primitives_from_tf: true
  marker_prefix: ""
  chain_root: "three_dof_planar_link0"
  chain_tip: "three_dof_planar_eef"
  joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3
  task_monitoring:
    active: 1
    publish_rate: 150.0

#trajectory controllers
position_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3

    gains:
        three_dof_planar_joint1: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint2: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint3: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }

    constraints:
        goal_time: 1.0

    state_publish_rate: 25

velocity_joint_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3

    gains:
        three_dof_planar_joint1: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint2: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint3: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }

    constraints:
        goal_time: 1.0

    state_publish_rate: 25
