joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

position_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - three_dof_planar_joint1
        - three_dof_planar_joint2
        - three_dof_planar_joint3

    gains:
        three_dof_planar_joint1: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint2: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }
        three_dof_planar_joint3: { p: 10.0, d: 2.5, i: 0.1, i_clamp: 1 }

    constraints:
        goal_time: 1.0

    state_publish_rate: 25
